language: csharp
solution: SampleWebAPI.sln
install:
  - nuget restore SampleWebAPI.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script: 
  - xbuild /p:Configuration=Release SampleWebAPI.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./SampleWebAPITests/bin/Release/SampleWebAPITests.dll

deploy:
  username: $azure_deployment_user
  password: $azure_deployment_password
  site: "pl-samplewebapi-demo"
  - provider: azure_web_apps
    verbose: true
    slot: "pl-samplewebapi-staging"
    on: dev
  - provider: azure_web_apps
    verbose: true
    slot: "pl-samplewebapi-prod
    on: master

